import { Category, Language } from './types';

export const CATEGORIES: Category[] = [
    { id: 'alphabet', name: 'الحروف الأبجدية', icon: 'fas fa-font' },
    { id: 'basics', name: 'الكلمات الأساسية', icon: 'fas fa-star' },
    { id: 'greetings', name: 'التحيات والتعارف', icon: 'fas fa-handshake' },
    { id: 'numbers', name: 'الأرقام', icon: 'fas fa-sort-numeric-down' },
    { id: 'colors', name: 'الألوان', icon: 'fas fa-palette' },
    { id: 'family', name: 'العائلة', icon: 'fas fa-users' },
    { id: 'food', name: 'الطعام والشراب', icon: 'fas fa-utensils' },
    { id: 'time', name: 'الوقت والأيام', icon: 'fas fa-clock' },
    { id: 'weather', name: 'الطقس', icon: 'fas fa-cloud-sun' },
    { id: 'home', name: 'المنزل', icon: 'fas fa-home' },
    { id: 'shopping', name: 'التسوق', icon: 'fas fa-shopping-cart' },
    { id: 'body', name: 'أجزاء الجسم', icon: 'fas fa-child' },
    { id: 'clothing', name: 'الملابس', icon: 'fas fa-tshirt' },
    { id: 'places', name: 'الأماكن والمدينة', icon: 'fas fa-city' },
    { id: 'transportation', name: 'المواصلات', icon: 'fas fa-bus-alt' },
    { id: 'work', name: 'العمل', icon: 'fas fa-briefcase' },
    { id: 'education', name: 'التعليم', icon: 'fas fa-graduation-cap' },
    { id: 'travel', name: 'السفر', icon: 'fas fa-plane-departure' },
    { id: 'health', name: 'الصحة', icon: 'fas fa-heartbeat' },
    { id: 'nature', name: 'الطبيعة', icon: 'fas fa-leaf' },
    { id: 'animals', name: 'الحيوانات', icon: 'fas fa-paw' },
    { id: 'hobbies', name: 'الهوايات والأنشطة', icon: 'fas fa-paint-brush' },
    { id: 'sports', name: 'الرياضة', icon: 'fas fa-futbol' },
    { id: 'music_arts', name: 'الموسيقى والفنون', icon: 'fas fa-music' },
    { id: 'technology', name: 'التقنية والإنترنت', icon: 'fas fa-laptop-code' },
    { id: 'emotions', name: 'المشاعر والأحاسيس', icon: 'fas fa-grin-beam' },
    { id: 'verbs', name: 'الأفعال الشائعة', icon: 'fas fa-running' },
    { id: 'adjectives', name: 'الصفات الوصفية', icon: 'fas fa-magic' },
    { id: 'restaurant', name: 'في المطعم', icon: 'fas fa-concierge-bell' },
    { id: 'daily_routines', name: 'الروتين اليومي', icon: 'fas fa-calendar-check' },
    { id: 'countries', name: 'الدول والقوميات', icon: 'fas fa-globe-americas' },
];

export const LANGUAGES: Language[] = [
    { code: 'en-US', name: 'English' },
    { code: 'fr-FR', name: 'French' },
    { code: 'it-IT', name: 'Italian' },
    { code: 'es-ES', name: 'Spanish' },
    { code: 'de-DE', name: 'German' },
    { code: 'ru-RU', name: 'Russian' },
    { code: 'tr-TR', name: 'Turkish' },
    { code: 'zh-CN', name: 'Chinese' },
    { code: 'ja-JP', name: 'Japanese' },
    { code: 'ko-KR', name: 'Korean' },
];

export const AVATAR_EMOJIS = ['👩‍💻', '👨‍💻', '🧑‍🏫', '👨‍🎓', '👩‍🎓', '🤔', '😊', '🥳', '😎', '🤓', '🤩', '😇', '🦊', '🦉', '🚀', '🤖', '🤯', '🧐', '🤠', '🧑‍🚀', '🧑‍🎨', '🕵️', '💡', '🌍', '🪐', '🎮', '🐻', '🦁', '🦄', '🐼', '🐨', '🐰'];